import mongoose from "mongoose";
const postSchema = new mongoose.Schema({
    title: { type: String, required: true },
    circle: { type: String, required: true },
    body: String,
  },
  { collection: "posts" }
);
export default postSchema;
// _id will be auto generated by MongoDB