import mongoose from "mongoose";
const replySchema = new mongoose.Schema({
    post: { type: String, required: true },
    body: String,
  },
  { collection: "replies" }
);
export default replySchema;
// _id will be auto generated by MongoDB